### ISSUE TITLE
Should the name of oneof groups be lowerCamelCase?

### ISSUE THREAD

**Issue by Vinzius** [bufbuild/protobuf-es#206]
Hi Team,

Thanks for the work!

I tried generating Typescript from our Protobuf, and I wondered if it was on purpose to not have `lowerCamelCase` applied to the name of the oneof groups?

I did some digging in the code, but couldn't locate where the logic is applied.

For instance, the message:

```protobuf
message ResourceRequest {
  string name        = 1;
  oneof  ProjectIdentifier {
    string project_id      = 2;
  }
}
```

would end up like this:

```typescript
export class ResourceRequest extends Message<ResourceRequest> {
  name = "";
  ProjectIdentifier: {
    value: string;
    case: "projectId";
  } | { case: undefined; value?: undefined } = { case: undefined };
}
```

So it results with `ProjectIdentifier`, while I would expect to have `projectIdentifier`.

Thanks :-) 

Ping @remyleone

**Comment by timostamm** [comment]
Hi Vincent, thanks for bringing this up. 

the name for the `oneof` is generated here: https://github.com/bufbuild/protobuf-es/blob/f526ea6f733539a4e4a893f29720e3e8d706cb60/packages/protoc-gen-es/src/typescript.ts#L133

And `localName()` is defined here: https://github.com/bufbuild/protobuf-es/blob/f526ea6f733539a4e4a893f29720e3e8d706cb60/packages/protobuf/src/private/names.ts#L24-L32

The conversion to `lowerCamelCase` happens here:

https://github.com/bufbuild/protobuf-es/blob/f526ea6f733539a4e4a893f29720e3e8d706cb60/packages/protobuf/src/private/names.ts#L148-L152

The most common convention is to use `snake_case` for field names and `oneof` names, so this works out pretty nicely if you follow our [style guide](https://docs.buf.build/best-practices/style-guide#messages).  If you rename your `oneof` to `project_identifier`, it will be generated as `projectIdentifier`.

In this specific case, it would be nice if we converted `ProjectIdentifier` to `projectIdentifier`, but there are other cases where it isn't as clear-cut. For example, a `message foo_bar` will generate as `class foo_bar` - would it also be appropriate to turn that into `lowerCamelCase`? 

The naming logic could become quite complex if we tried to normalize all possible naming conventions. That would make it hard to port and is likely to increase bundle size. So I hope you understand that this limitation is intentional. Perhaps it would be an option to follow the style guide here, and rename the `oneof` group?

**Comment by Vinzius** [comment]
Thanks for the thoughtful response!

I agree that the lowerCamelCase should work if the style guide is properly followed, which is not in this case/example (legacy reason).

I was under impression that the logic would force the first letter into lower case. But by reading `protoCamelCase` it's indeed not the case, and so working as designed.

Thanks for taking the time to answer!
Have a nice week-end
