### ISSUE TITLE
Explicitly omitting `undefined` values

### ISSUE THREAD

**Issue by faustbrian** [bufbuild/protobuf-es#208]
Hey, I currently have an issue with the generated classes because they have default values and I can't seem to force certain values to be `undefined` for when I need them to be. So the code that is being generated is based on proto files that I don't control and I call them like `new ResponseInfo({ ... })` to get an instance of that response which is then passed onto another entity I don't control that calls `toBinary()` on it. The result then includes default values that should be omitted.

```ts
ResponseInfo {
    data: '0.0.0',
    version: '0.0.0',
    appVersion: 0n,
    lastBlockHeight: 0n,
    lastBlockAppHash: Uint8Array(0) []
}
```

The issue is that I need to be able to omit `lastBlockHeight` and `lastBlockAppHash` from the response because otherwise the application that receives the response will panic and terminate. Is there any way for me to omit those properties if their value is set to `undefined`? Currently they are being set to 0 and an empty array rather than being excluded.

**Comment by timostamm** [comment]
Hey Brian, thanks for the report!

So you probably have a proto file similar to this:

```proto
syntax = "proto3";
package hello;
message ResponseInfo {
    string data = 1;
    string version = 2;
    uint64 app_version = 3;
    uint64 last_block_height = 4;
    repeated bytes last_block_app_hash = 5;
}
```

Let's take a look at the default values:

```ts
const ri = new ResponseInfo();
console.log("lastBlockHeight", ri.lastBlockHeight)
console.log("lastBlockAppHash", ri.lastBlockAppHash)

// this will print:
// lastBlockHeight 0n
// lastBlockAppHash []
```

The reason is that scalar types (like string and int64) have _intrinsic_ default values in proto3 syntax. You can find the documentation [here](https://developers.google.com/protocol-buffers/docs/proto3#default). Those default values are actually omitted when you serialize to binary:

```ts
const ri = new ResponseInfo();
console.log("toBinary().length", ri.toBinary().length);

// this will print:
// toBinary().length 0
// doesn't get any shorter than 0 - we already omitted everything
```

And if somebody deserializes the same (empty) byte array, they will see the same default values in their deserialized message. We cannot change this behavior because this is the contract between both parties, defined in protobuf. 

If you did control the proto files, you could make the fields optional: 

```proto
    optional uint64 last_block_height = 4;
    optional repeated bytes last_block_app_hash = 5;
```

This would change the contract, the fields would become optional in TypeScript (accept undefined), and there would be a distinction between `0`, `undefined`, and any other value on the wire (i.e. the binary format).

Since you don't control the proto files and neither the receiving application, it seems that the proto file and the receiving application either don't want you to provide default values, or that the receiving application has a bug.

Closing this, but if I missed the point, please do let us know!
