### ISSUE TITLE
Request: Global Registry of generated types

### ISSUE THREAD

**Issue by dnsco** [bufbuild/protobuf-es#222]
I see that there is createRegistry that works with a FileDescriptorSet.

Since I'm already Generating the code, is there a way that it could be registered at load time like how the google protobufs attatch to window.proto?

I'm trying to do some stuff with runtime reflection, right now, I'm hand coding a Record<string, MessageType> so as to not have to figure out how to load a filedescriptorset.bin with create-react-app's webpack configuration.

Thanks again for the library! Love where it's going!

**Comment by timostamm** [comment]
Hey Dennis, 

it is very unlikely that we will ever add global registration at load time for the following reasons:
1) it is a [side effect](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) that hampers tree-shaking
2) it leads to runtime errors for legitimate use cases

To elaborate on point 2: Protobuf for Go uses a global registry, and users often run into issues caused by it. There is even a [FAQ](https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict) entry about protocol buffer namespace conflicts.

Instead of handwriting a `Record`, perhaps you could also use `createRegistry()`? 

```ts
import { createRegistry } from "@bufbuild/protobuf";
import { MessageA, MessageB } from "./generated"

const registry = createRegistry(
  MessageA, 
  MessageB,
);
```

This is obviously still a manual setup. You could easily write a plugin that generates this code for you, though. Take a look at [protoc-gen-connect-web](https://github.com/bufbuild/connect-web/blob/main/packages/protoc-gen-connect-web/src/protoc-gen-connect-web-plugin.ts) for an example for a simple plugin.

While we think that a global registry is not a good fit, especially for ECMAScript, we absolutely are interested to hear about use cases and and finding a better approach. Let's keep this open, and thank you for the request!

**Comment by dnsco** [comment]
Thanks for pointing me in the right direction!
