### ISSUE TITLE
Deterministic Serialization Guarantees

### ISSUE THREAD

**Issue by faustbrian** [bufbuild/protobuf-es#251]
I use this library in an application that needs deterministic serialization guarantees, which protobuf doesn't offer out of the box based on something like https://gist.github.com/kchristidis/39c8b310fd9da43d515c4394c3cd9510.

So my question is if there are cases with the implementation in this repository where the same message with the same input over time could result in a different (binary) output and if so, what types would cause this and would avoiding them resolve this? Thanks!

**Comment by timostamm** [comment]
Hey Brian, thanks for opening this issue!

in protobuf-es, fields are always serialized in the order of their field number, but there are a couple of things to look out for:

### map fields

Map fields are are iterated over with `Object.entries()` when serializing. That means that the fields will be serialized in the order they were added to the map:

```ts
let m = {};
m.a = 1;
m.b = 1;
console.log(Object.keys(m)); // ["a", "b"]

m = {};
m.b = 1;
m.a = 1;
console.log(Object.keys(m)); // ["b", "a"]
```

In both cases above, `m` could be considered to be the same input, but they result in different binary output.

### string normalization

`\u00F1` and `\u006E\u0303` are two representations for the letter `ñ`. The latter one is the decomposed form, but both could be considered the same input. Depending on your use case, you may want to [normalize strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize), strip any potential BOM in the input, or even normalize line endings. 

### unknown fields

When protobuf-es parses a message from binary format, any fields that it does not recognize are stored in a hidden property on the message object, and included again when serializing. Since these fields are unknown to the generated code, you may want to ignore them for your use case. You can do so by setting the binary 

You may want to ignore unknown fields for your purpose. You can do so with the option `readUnknownFields: false`:

```ts
MyMessage.fromBinary(bytes, {
  readUnknownFields: false
})
```

You can also discard unknown fields _per message_ with `proto3.bin.discardUnknownFields(myMessage)`.


### google.protobuf.Any

If you parse and serialize an `Any`, the message data it holds will not be parsed into a message. So if you have data in an `Any` that was produced by another implementation, you will be subject to the quirks of this implementation, because protobuf-es only passes the data through.


### changes in protobuf-es

I don't see why we would ever change the order of serialization. But if it turns out we missed a bug somewhere, a fix could potentially result in different serialization output.

**Comment by timostamm** [comment]
We match other implementations with the handling of unknown fields, it's a feature that allows messages to be processed by old generated code while preserving new fields. See the [official documentation](https://developers.google.com/protocol-buffers/docs/proto3#unknowns) for a few more details.

You can use the following to determine whether a message has unknown fields:

```ts
const hasUnknownFields: boolean = proto3.bin.listUnknownFields(myMessage).length > 0
```

**Comment by timostamm** [comment]
protobuf-**ts** does have an option to raise an error, but this was deliberately not ported over to reduce complexity. 

Retaining fields are generally considered a desirable behavior when you want to provide good backwards compatibility for an API. They will not affect the `Message` in any way, they are just kept in memory until you serialize again. If you don't want them, you can set `readUnknownFields: false`.

If you really need to error on unknown fields, you can do so with:

```ts
// run this before you parse anything
proto3.bin.onUnknownField = (message, no, wireType) => {
  throw new Error(`got unknown field number ${no} (${WireType[wireType]}) for ${message.getType().typeName}`);
}
```
