### ISSUE TITLE
Make `protoplugin` support asynchronous code generators

### ISSUE THREAD

**Issue by fubhy** [bufbuild/protobuf-es#278]
There are probably other use-cases for this too but I'm struggling with `readline` atm. which doesn't have a synchronous interface to conveniently read files line-by-line. I need that for ingesting a text file that contains a list of encoded proto messages to feed into test cases.

PR: https://github.com/bufbuild/protobuf-es/pull/277

**Comment by timostamm** [comment]
Hm, the only case where async speeds things up is for work that is I/O bound. Obviously plugins need to read a CodeGeneratorRequest from stdin and write a CodeGeneratorResponse to stdout, but that can't be parallelized.

Yes, a plugin could read sidecar files, but that really brakes the plugin contract. A plugin could manipulate existing files, but that also brakes the plugin contract. A plugin could import() a dependency, and only use it if it's present, but that's bad for reproducible code generation. 

So in my mind, keeping the code generators sync means we [keep it simple](https://en.wikipedia.org/wiki/KISS_principle), which is a good thing. We really want to discourage from accessing the file system or network, because that leaves the door open to compile plugins to WASM, and run them in a secure sandbox.

Obviously there will always be special use cases where it is fine to break the plugin contract. But in your specific case, wouldn't it be fine to use something like this?

```ts
import {readFileSync} from "fs";

const lines = readFileSync("foo.txt", "utf8").split("\n");
```

Node's readline package is really more intended for reading from an interactive command line, similar like the [GNU readline library](https://tiswww.case.edu/php/chet/readline/rltop.html), so I think this approach is quite a bit simpler, and I don't see any real drawbacks in this case - what do you think?

**Comment by fubhy** [comment]
Yeah, I'm aware that the primary use case for the `readline` package is `stdin` but that's exactly why I chose it because I'm sharing the same code between a bash script (that pipes input to some utils I am already using) and this one.

I can then simply replace `input: process.stdin` with `input: fs.createReadStream` and re-use all the existing logic.

But I can see where you are coming from regarding KISS.

Although, as side-effects are already possible as this is not running in a completely isolated VM, I'd argue that there's no fully enforced plugin contract already anyways.

I can see though that reading other arbitrary files or calling `fetch` or other effectful operations might not be the most common case.

One thing I might argue is that by not allowing asynchronosity (which would be a rather simple change to the codebase), downstream implementations / plugins are actually becoming more difficult for those cases where side-effects are desirable because then we might see weird sync traps being used to circumvent that limitation like e.g. https://github.com/sindresorhus/make-synchronous

**Comment by fubhy** [comment]
One other option for my particular usecase would be to allow `buf` itself to receive (and forward) a stdin handle.

**Comment by smaye81** [comment]
@fubhy I don't think we are going to implement this at this time due to some of the points @timostamm mentioned above.  If something changes in your use case though, please let us know.
