### ISSUE TITLE
Message<T> JsonValue serialization override incompatible with common TS documentation generators

### ISSUE THREAD

**Issue by Wurden** [bufbuild/protobuf-es#373]
Using protobuf-es (protoc-gen-es) to generate TypeScript code, the generated classes are incompatible with common documentation generators such as [tsoa](https://github.com/lukeautry/tsoa).

We build services that support both regular REST APIs and expose the same as gRPC endpoints. For the REST APIs OpenAPI and Swagger are used to create interactive documentation.
Tsoa supports providing defined types, interfaces or classes as model for a request, however the way the JsonValue is serialized in the protobuf-es library renders only useless documentation.

Consider this protobuffer message:
```
message MyApiRequest {
  string id = 1; // Internal tracking id
  string account_number = 2; // Reference to the account
}
```

It generates a class with the signature:
`export class MyApiRequest extends Message<MyApiRequest> {...}`

I can provide the class as the request body and annotate it to be used for documentation:
```
public async MyApi(
    @Request() request: MyApiRequest
  ): Promise<MyApiResponse> {
    return this.processApiRequest(request);
}
```

But the generated OpenAPI schema only shows a generic any type JsonValue:
```
"MyApiRequest": {
  "$ref": "#/components/schemas/JsonValue",
},
```
and not any of the actual parameters provided in the *.proto file.

The base class `export declare class Message<T extends Message<T> = AnyMessage>` in dist/message.d.ts overrides default serialization behavior of `protected toJSON(): JsonValue;` and I believe that is the culprit here.

If I create another class that extends the generated class like:
```
import { MyApiRequest as MyApiRequestGenerated } from "../gen/api/v1/api_pb";

class MyApiRequest extends MyApiRequestGenerated {
  protected toJSON() {
    return {
      id: this.id,
      accountNumber: this.accountNumber,
      // other properties...
    }
  };
}
```

tsoa is now able to generate an API specification that shows the correct parameters in OpenAPI and in the Swagger UI. So that's a workaround to still use the protobuf-es library although it kinda defeats the purpose of using generated code.

If I switch to another TypeScript protobuffer library like https://github.com/stephenh/ts-proto and use protoc-gen-ts_proto the generated interfaces/classes works without any issues to also generate REST API documentation

**Comment by timostamm** [comment]
Hey Christopher, the generated code implements two serialization formats:

1. the [wire format](https://protobuf.dev/programming-guides/encoding/) - a simple but efficient binary serialization format
3. the [canonical JSON format](https://protobuf.dev/programming-guides/proto3/#json) - a well-defined mapping between protobuf fields and JSON properties

There is a [conformance test suite](https://github.com/bufbuild/protobuf-es/tree/main/packages/protobuf-conformance) that implementations can run against, to make sure that a format is implemented correctly.  
This means you could have protobuf-es on one side, Google.Protobuf for C# on the other side, and they can talk to each other reliably, and you would never have to deal with serialization issues. This is true for simple strings, but also for types that regular JSON does not support, for example 64-bit integers, or byte arrays. 

The canonical JSON format defines how these types are mapped to JSON. It's important to realize that a parsed message object may look different from a serialized JSON object, because protobuf has more types available than JSON. That means that if you call `JSON.stringify()` on a message, you serialize the _runtime_ representation of this message, and you lose the interoperability with other implementations.

ts-proto actually has several options to tweak how a message is represented, and you will get varying JSON output if you call `JSON.stringify()` depending on those options. If you use the result of `JSON.parse()` as a ts-proto generated message, you are very likely to have type mismatches. With ts-proto, you are supposed to serialize to the JSON format with `MyApiRequest.toJSON()`, and parse with `fromJSON()`. ts-proto does not generate types for the JSON format.

With protobuf-es, it is the same. You should use `myApiRequest.toJson()` and `MyApiRequest.fromJson()` to use the canonical JSON format. But you _can_ actually use `JSON.stringify(myApiRequest)` with protobuf-es, because we override `toJSON()` to use canonical serialization with `JSON.stringify`.

I hope this sheds some light on the situation. I agree that types for the JSON representation would be useful for your use case with `tsoa`. I'm amazed that it picked up our override of `toJSON()`!

**Comment by smaye81** [comment]
hi @Wurden.  Going to close this issue since hopefully @timostamm shed some light on why things are behaving as they are.  To help visualize a bit more of what we mean by conformance, we've created a repository called [Protobuf Conformance](https://github.com/bufbuild/protobuf-conformance) which runs various libraries through the conformance test suite. This might provide a bit more info on how the other implementations behave.

If you run into any other issues, though or have additional questions, give us a shout.
