### ISSUE TITLE
Proposal: opt-out the '_pb' suffix plugin option

### ISSUE THREAD

**Issue by hugebdu** [bufbuild/protobuf-es#400]
Alternatively make it customizable, but with an option to drop it completely.
I guess the suffix makes sense when the generated sources reside aside with the developer code.
In our case we place it into a separate folder, so omitting the suffix is preferable.

Thanks!

**Comment by smaye81** [comment]
Hi @hugebdu.  Appreciate the request.  This is actually a bit more involved than it initially appears.  For example, our Connect-ES plugin generates import statements with the assumption that Protobuf-ES is generating files with the `_pb` suffix.  If we were to allow this to be an option there, it would then have to be an option in any plugin that was using Protobuf-ES generated types and users would need to make sure they were passing the same suffix to each plugin.

We need the filenames to be stable and predictable so that downstream plugins aren't affected, so unfortunately I don't think this is something we plan to implement.  Thanks again for the request, though.
