### ISSUE TITLE
FR: Assign enum by string value

### ISSUE THREAD

**Issue by jamesshannon** [bufbuild/protobuf-es#420]
The root cause of my logging feature request was that my datastore (mongodb) is current storing my protobuf enums as a string, which is then used to create a message.

```
message Msg {
  Status status = 1;
 
  enum Status {
    NEW = 1;
  }
}


// in javascript
new Msg({'status': 'NEW'});
```

(I'll add that the above works perfectly, and only when trying to create a binary representation (`.toBinary()`) do I get the `Error: invalid int 32: string` error. This wasted even more time because fastily isn't good about capturing and surfacing errors. I think there's a FR to be more aggressive about "type validation" in protobuf-es and also one to capture and log errors in the `ConnectRouter`, but I'm limiting myself to three per day.)  

 *Expectation*
Protobuf-es should be a bit more lenient about what it accepts, especially with `strings` for enum values, in which case it should try using `enum_class[field_value]` to get the integer.

**Comment by timostamm** [comment]
Similar to https://github.com/bufbuild/protobuf-es/issues/421, parsing a protobuf message from a JSON string should be done via `MyMessage.fromJsonString()`. This will also give you other helpful options like ignoring unknown fields, or providing a type registry to parse `google.protobuf.Any`. 

For validation of `new Msg({'status': 'NEW'})`, we are relying on TypeScript for compile-time checks. It would be beneficial to raise an error here in the CTOR instead of when serializing, but it would still be a runtime error.

For the time being, we do not plan to add runtime validation in the CTOR.
