### ISSUE TITLE
FR: Support snake_case field names

### ISSUE THREAD

**Issue by jamesshannon** [bufbuild/protobuf-es#421]
protobuf-es should support field names in snake_case. At the least it should "parse" documents provided in the constructor in a way that allows for snake_case.

My use case is grabbing a lot of pre-existing "JSON protobufs" and then using them within javascript. These were originally created as protobufs but to store them in mongodb I had to convert to JSON. The python module I use keeps the `snake_case` field naming convention (which *is* the [protobuf style standared](https://protobuf.dev/programming-guides/style/#message-field-names)). The problem is that when I grab from mongo and pass the JSON object to the `protobuf-es` message Constructor it helpfully ignores the unexpected field names and doesn't set the field. This was especially confusing because most fields were set properly (those that were only one word and thus had consistent naming).

*Expecation*
protobuf-es should have a flag to switch between snake case and loweCamelCase. I thought about suggesting that it should simply accept snake_case (or provide a helper conversion function) but then I'm just putting off the the problem until I save the records back and try to read them with Python.

**Comment by jamesshannon** [comment]
Just noticed this statement in your comments for `protobuf/src/json-format.ts`:

> Proto3 JSON parsers are required to accept both the converted lowerCamelCase name and the proto field name.

**Comment by timostamm** [comment]
For your use case, use `MyMessage.fromJson()`. It supports all [valid permutations of JSON input](https://protobuf.dev/programming-guides/proto3/#json), as confirmed by the [protobuf conformance test suite](https://github.com/bufbuild/protobuf-conformance).

We do not support proto fields names in the constructor, because we believe there should be only one representation at runtime for simplicity and ease of use. We are explaining the reasons for not supporting a plugin option either [in the FAQ](https://github.com/bufbuild/protobuf-es/blob/main/docs/faq.md#what-is-your-stance-on-adding-options-to-the-plugin).

**Comment by jamesshannon** [comment]
Thanks. For the record, I think this was another case of not realizing that `Message({json_object})` and `Message.fromJson({json_boject})` have two very different behaviors.
