### ISSUE TITLE
Feature Request: Message#toProto

### ISSUE THREAD

**Issue by bgreenlee** [bufbuild/protobuf-es#440]
Before I attempt to build this myself, I thought I'd ask: is there any way to take a `Message` (or perhaps a `MessageType`?) and produce the original proto schema?

My use case is that I'm trying to automatically register schemas, via a received message, with the Confluent Kafka Schema Registry. Their Python and Go clients have a method to serialize a proto message by [generating the schema from the message](https://github.com/confluentinc/confluent-kafka-go/blob/3d9047adc3ae9b41069988298906624497175962/schemaregistry/serde/protobuf/protobuf.go#LL165C36-L165C36), and then looking that schema up in the registry to get the ID. I'm attempting to replicate this in Typescript with [@kafkajs/confluent-schema-registry](https://github.com/kafkajs/confluent-schema-registry), which is a fairly light wrapper around the Schema Registry API, and as such requires you pass in the proto schema as a string.

**Comment by timostamm** [comment]
Hey @bgreenlee, there is no such feature, and going from a generated message to proto source is a bit involved.

Some background: Protobuf source files are typically compiled to a set of descriptors (which themselves are protobuf messages), and passed to a code generator plugin. 

Many implementations embed the descriptors into the generated code. The feature is most often used to read custom options at runtime, but it can also be used for other purposes. 

It is possible to reconstruct a proto source file from descriptors, but it is not trivial. The Confluent Go client uses the [protoprint package](https://pkg.go.dev/github.com/jhump/protoreflect/desc/protoprint) for this purpose. The author of this package called out the following complicated parts:
- Sorting elements - particularly trying to reproduce the original sort order
- Custom options - which do not have first-class support in protobuf-es
- Formatting - particularly for custom options

I think that custom options will also be complicated by the fact that they are given in the protobuf text format, and I don't believe a JS implementation for it exists. Another hurdle is that protobuf-es does not embed descriptors into the generated code because that would increase bundle size for web clients. Instead, it embeds a minimalistic set of `FieldInfo` (you can see them [here](https://github.com/bufbuild/protobuf-es/blob/128c153462b6f7527f1de64c35317d9944cdbb97/packages/protobuf-test/src/gen/js/extra/example_pb.js#L27-L32)).

If very basic reconstruction of the proto source is sufficient for you, walking through `FieldInfo` can be sufficient. The main missing piece will be custom options. Alternatively, you could create a small plugin that generated file descriptors for you ([this example](https://gist.github.com/timostamm/a7bfee43d7a88809dc682ccc3b465ab3) could be a start), and then implement something similar to the `protoprint` package.

But taking a step back, this does seem quite complex. From a quick peek at the Python implementation, it looks to me that it does not reconstruct the proto source file, but rather simply registers the descriptors ([serialized and base64 encoded here](https://github.com/confluentinc/confluent-kafka-python/blob/5936d0b465ad45eaff9c02ed7829f02d7c797cd7/src/confluent_kafka/schema_registry/protobuf.py#L128)). 
If I read that correctly and if this is sufficient for your case, this approach is definitely much more straight-forward to implement. 

You can use a plugin as described above, but you could also generate a binary descriptor set at build time (along with generating code) and wrap your client with a small function that registers (descriptor) schema data.

I hope this gives you some pointers to get started. I'm happy to help out with more details where I can.

**Comment by bgreenlee** [comment]
Thank you for the detailed reply! I looked into it a bit and it did seem quite involved. For now we are going with having folks pre-register their schemas (which I think is the way to go in the end, given the lack of support for custom options in most libraries, which we're using for metadata like owner, description, and PII).

I'll close this ticket for now.
