### ISSUE TITLE
rewrite_imports: Odd behavior with relative imports

### ISSUE THREAD

**Issue by NfNitLoop** [bufbuild/protobuf-es#484]
In a library I wrote, I configure a relative rewrite [like this][1], starting with `./`, but the [generated code][2] imports from `../`. 

Initially, I thought that maybe there was some relative path magic going on and it decided to go "up" a directory.  However, if I change the configuration to import from `../`, the generated code tries to import from `.../`, which is not a valid path.

So, it seems like there's either a bug w/ the handling of relative paths, or I'm misunderstanding how they work. 

[1]: https://github.com/NfNitLoop/deno-buf-connect/blob/74de9f7e4b1e8533db3d08d644cd571f887ef747/examples/oak-server-and-client/buf.gen.yaml#LL18C74-L18C74
[2]: https://github.com/NfNitLoop/deno-buf-connect/blob/74de9f7e4b1e8533db3d08d644cd571f887ef747/examples/oak-server-and-client/gen/protos/Example_pb.ts#L7

**Comment by smaye81** [comment]
The import paths are written in a way that make them relative to the file importing them. So, for example:

```typescript
 * - foo/foo.js
 * - baz.js
```
If `foo.js` wants to import `baz.js`, we return `../baz.js` because it's assumed that the files are relative to the `out` directory specified in your buf.gen.yaml.

So, in your case, it's assuming the full path for your import rewrite is `gen/bufbuild/protobuf.ts`. It knows the importing file lives at `gen/protos/Example_pb.ts`, so to make that file relative, it needs to go up one directory, hence the `../bufbuild/protobuf.ts`. 

The example you link above seems correct to me. I haven't been able to see the three dot behavior you specify above though.

**Comment by NfNitLoop** [comment]
> it's assumed that the files are relative to the out directory 

That's what I figured. So I was very surprised to see it generate a file with `…/` as a path part! I actually *wanted* to specify `rewrite_imports=@bufbuild/protobuf:../other/path/`, but that wasn't working.

… at least, that's how I *remember* it.  Of course, now that I try to reproduce it today, it's working as I'd expect. 🤦 

Y'all aren't gaslighting me by fixing it on buf.build and then saying it was never a problem, are you?  😆

Anyway, this is working as expected. I'll close this issue. Thanks!

**Comment by smaye81** [comment]
![image](https://user-images.githubusercontent.com/911455/236965963-63669052-691a-48dd-98a0-44879884e708.png)

Haha, I promise!  If you are able to recreate the issue or see something else wrong, feel free to reopen though.
