### ISSUE TITLE
can we enable discussions?

### ISSUE THREAD

**Issue by unicomp21** [bufbuild/protobuf-es#505]
@timostamm how was the .proto parser generated?

**Comment by timostamm** [comment]
Currently, we don't have discussions enabled for this project, but we're happy to discuss in issues, or [in Slack](https://buf.build/links/slack) 🙂 

This project does not parse .proto files at all. When generating code, a compiler like `protoc` or [buf](https://github.com/bufbuild/buf) parses .proto files into [descriptors](https://protobuf.com/docs/descriptors). A set of descriptors is then passed to a code generator plugin via the [plugin contract](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/plugin.proto).

It is possible to generate a parser from the [language spec](https://protobuf.com/docs/language-spec). There are some example on the linked page.

**Comment by unicomp21** [comment]
got it, thanks!  @timostamm how is the .proto parser generated for buf?

**Comment by timostamm** [comment]
Here's the compiler, it's open source: https://github.com/bufbuild/protocompile It is using [yacc](https://pkg.go.dev/golang.org/x/tools/cmd/goyacc) to generate [the parser](https://github.com/bufbuild/protocompile/blob/2b297241d0ffe9e749832e40b9715c678a33eb28/parser/proto.y.go) from a [yacc definition](https://github.com/bufbuild/protocompile/blob/2b297241d0ffe9e749832e40b9715c678a33eb28/parser/proto.y). The [language spec](https://protobuf.com/docs/language-spec) uses EBNF because it's a bit easier to read.

**Comment by smaye81** [comment]
Going to close this @unicomp21 but feel free to reach out if you have other questions.
