### ISSUE TITLE
in Connect-Web, Enums are returned as strings

### ISSUE THREAD

**Issue by v-morlock** [bufbuild/protobuf-es#507]
According to the FAQ and also as defined in the generated typescript typings, i was expecting enums to be returned as integers. However, while testing i recognized the enums are being returned as string values - is this expected? I'm calling a grpc-web API through connect-web.

Thanks!

**Comment by v-morlock** [comment]
Hi Timo, thanks a lot for your quick reply. What you say makes total sense - however, shouldn't this then also be reflected in the generated typescript enums? The generated enums were in the form of 

```ts
export enum DeviceState {
  /**
   * @generated from enum value: DEVICE_STATE_NOT_DEFINED = 0;
   */
  NOT_DEFINED = 0,

  /**
   * @generated from enum value: DEVICE_STATE_OFFLINE = 1;
   */
  OFFLINE = 1,

  /**
   * @generated from enum value: DEVICE_STATE_INITIALIZE = 2;
   */
  INITIALIZE = 2

}
```

however at runtime, strings were returned - thus matching on the generated enums isn't working...

**Comment by timostamm** [comment]
At runtime, when you receive a response with @bufbuild/connect-web, the messages are not simply parsed with JSON.parse(). What happens is more similar to [Zod](https://zod.dev/), where your schema can contain types   like `bigint`, which cannot be serialized or parsed with JSON, and where the TypeScript type does not reflect the JSON representation 1:1.

The mapping between protobuf fields and JSON is defined [here](https://protobuf.dev/programming-guides/proto3/#json). This mapping is used by all conforming protobuf implementations, so that you have the guarantee that you can parse or produce protobuf JSON with any of them.

To parse a protobuf message from JSON, every generated message has a `fromJsonString()` method. It is called automatically when you receive a response. There is also a `toJsonString()` method for serialization. The available methods are [documented here](https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#serializing-messages).

Hope this sheds some light onto what is going on 🙂
