### ISSUE TITLE
Typed JSON

### ISSUE THREAD

**Issue by Palmik** [bufbuild/protobuf-es#508]
It would be nice and useful to have types generated for objects produced by `toJson`, rather than just having a generic type like today.

**Comment by smaye81** [comment]
Hi @Palmik this has been requested a few times. It's probably something we should consider. Going to keep this open so we can eventually prioritize.

**Comment by FND** [comment]
FWIW, I've run into the same issue and resorted to [deriving data structures from classes](https://www.typescriptlang.org/play?#code/PTAEHMEsDcFMDtQBcAWtQDMD2AbHWB3SecUAYxwEMBna0FSWAJ0qbJQE8A6HgKF8gBbAA5YmSUAG9QAWVi1K4dAF9MTLINAAiAAIAjAK4ZDkHABNgw9UiyGMWgNz8KNOgAVm1LIlgAPJAhmdHIKSgA8Hkxe8AB8UrygiaDwlIKwAPwAXKDUSEzE4E5JoIoZ2fAGgnrMRUmUZmZM8tRZoACCDU20TsrOVLTtnc2gfgHwQbLNpWEdjc1xkglJZFgG8Hkcrbn5JLWJ+GSUSJDeW3kFPfwgoDxcoAToBJTryFgQCMxH6JTIHMLoK3WlGIBVA3hwHGQaFAXX+ZGOcFAZiOPwwjHM1H4OFgEmRSEo2Ui0QAIijQABeeLFFJpbJaABSxK0ABololStkAIwAJgAzKzivU5rRsotisUVmsNnSAHKQJjQZ6UFls8UHI4neB0nFoJhaVW9ZROXjXW45N4PJHMGDoPE-bYGeEGLpqDRQ9Cw2Dwm3kfrUeT8JB-dBE7yk-EU0DhygAeXgEIinm8MScQf+g2F1GjkejcYTsy61BToGu2CYyHkxxIoGEztE-ro4I4geDUZReY4YQAKiN-IE6DHhMdvJQcCFqKU4pSe6N+5NQuh0lTxYkANoAaVgkOIoAAor4KAYzLAwgBrLdYDCgLvM0DnjiX+cTpQxAC62S7G63r97Ywmg+HFIxymJRVRXRIl1zeNO0-TcOFfGIwPAj8v3gvZQF6YpsjWY80XgWAzFTVsAM1Udx1KSNyKUUAAB9QBw2A8II41TR4XsyFgIca3Uf5xEYagAHIwSHUicEwKhSEgOh8Fyfg7UjMUkhpWA6UZFVBSULk+V4I0gA). However, that's not just brittle, it also feels like solving the problem at the wrong layer because the compiler should already know what these data structures look like.

<details><summary>source code</summary>

```typescript
// given the following class hierarchy...

import { Message } from "@bufbuild/protobuf";

class Person extends Message<Person> {
    name?: string;
    age?: number;
    address?: Address;
}

class Address extends Message<Address> {
    country?: string;
    location?: string;
}

// ... we want to generate a type containing only the respective data fields

const data: PersonData = {
    name: "JD",
    age: 123,
    address: {
        country: "Nirvana",
        location: "ether"
    }
};

// XXX: this contains a fair amount of redundant, brittle logic
type PersonData = Omit<Pick<Person, PersonDataFieldName>, "address"> & {
    address?: Pick<Address, AddressDataFieldName>;
};
type PersonDataFieldName = Exclude<keyof Person, keyof Message>;
type AddressDataFieldName = Exclude<keyof Address, keyof Message>;

// for reference

const field1: PersonDataFieldName = "age";
const field2: PersonDataFieldName = "address";
// @ts-expect-error 
const field3: PersonDataFieldName = "fromBinary";

const prop1: keyof Person = "age";
const prop2: keyof Person = "address";
const prop3: keyof Person = "fromBinary";

const { // inherited properties; for illustration purposes only
    clone,
    equals,
    fromBinary,
    fromJson,
    fromJsonString,
    getType,
    toBinary,
    toJson,
    toJsonString
} = new Person();
```

</details>

**Comment by timostamm** [comment]
This feature is implemented in the [upcoming version 2](https://github.com/bufbuild/protobuf-es/releases/tag/v2.0.0-alpha.1) by https://github.com/bufbuild/protobuf-es/pull/866.

**Comment by timostamm** [comment]
See the [documentation for JSON types](https://github.com/bufbuild/protobuf-es/blob/main/MANUAL.md#json-types).
