### ISSUE TITLE
Update Typescript to 5.1.6

### ISSUE THREAD

**Issue by shotamakino** [bufbuild/protobuf-es#524]
Hi team, 

Thank you for your creation!

I noticed typescript was updated in every other package except the protoplugin package. I was hoping to get an upgrade on this as well, as it's giving me some cascading issues external to this codebase.

https://github.com/bufbuild/protobuf-es/blob/6e067329bd4dee23d03042b5464075db71309aa3/packages/protoplugin/package.json#L40C5-L40C5

Thanks again!

**Comment by smaye81** [comment]
Hi, @shotamakino this is actually intended. Our `protoplugin` package provides the ability to transpile generated code so that you only need to write a plugin to generate TypeScript if desired. To accomplish this, we use an older, stable version of TypeScript to do the transpilation. More info [here](https://github.com/bufbuild/protobuf-es/blob/main/docs/writing_plugins.md#providing-generator-functions).

Also, just to verify -- you only really need to explicitly install `@bufbuild/protoplugin` if you plan on writing your own plugin. That being said, though, what issues are you seeing?

**Comment by shotamakino** [comment]
hi @smaye81 - ty! I was actually able to resolve my issue with some workspace configurations so I can close this issue now. I was running into an issue involving [this react issue](https://github.com/i18next/react-i18next/issues?q=Type+instantiation+is+excessively+deep) and typescript 4.5.6
