### ISSUE TITLE
null properties cause a `TypeError: Cannot read properties of null (reading 'length')`

### ISSUE THREAD

**Issue by jagobagascon** [bufbuild/protobuf-es#529]
Hi! I'm working on migrating our project from `google-protobuf` to `@bufbuild/protobuf` and one of the biggest rough edges I found is the way `@bufbuild/protobuf` treats the `null` values.

We are using Angular and `FormBuilder` to create forms and get the input values on submit. But Angular returns a `null` when an optional field was not set:

```ts
const formValues = this.form.value[this.entities.USER];
const user = new User({
  email: formValues[this.fields.EMAIL],            // 'user@user.com'
  givenName: formValues[this.fields.GIVEN_NAME],   // 'user'
  familyName: formValues[this.fields.FAMILY_NAME], // null
});
```

If I try to serialize this object with `user.toBinary()` then I get the following error:

```log
TypeError: Cannot read properties of null (reading 'length')
    at scalarTypeInfo (scalars.js:100:56)
    at writeScalar (binary-format-common.js:275:64)
    at Object.writeMessage (binary-format-proto3.js:49:44)
    at User.toBinary (message.js:74:13)
    at ...
```

I've seen that the library does work when we user `undefined` values, so doing something like this works fine:
```ts
user.familyName = formValues[this.fields.FAMILY_NAME] ?? undefined;
```

This makes the migration process a real pain, because **we will have to go through every form to make sure no `null` values are passed to a protobuf object**. Is there any reason for this?

**Comment by timostamm** [comment]
Hey Jagoba, the initializer object accepted by the `User` constructor is similar to the built-in type `Partial`, which makes all properties optional. This means that each property can be either the original type - or `undefined`. Passing `null` is not allowed, and you should see an error like the following when doing so:

> TS2322: Type 'null' is not assignable to type 'string | undefined'.

In your case, I assume that `form.value[string]` is an `any`, so the compiler does not not notice the problem. 

We do not accept `null` as an alternative to `undefined` because it waters down type safety. Less variance means that it's more difficult to pass in the wrong type inadvertently. Of course there are also advantages in cases like this, but it's not as clear-cut when looking at the big picture.

**Comment by jagobagascon** [comment]
Understood.

The way we build our forms using the form builder removes the type of the inner form controls, so we will have to fix that to avoid any unexpected error. Thanks for clarifying.
