### ISSUE TITLE
The `FileDescriptorSet` instance omits my option

### ISSUE THREAD

**Issue by czabaj** [bufbuild/protobuf-es#564]
Sorry if this is a noob question, I'm quite new to gRPC in general.

I'm in the process of writing a  _protoplugin_ for grpc-gateway client SDK, I decided to use the Protobuf-ES framework and it works really great, thanks for that 🙇 

I encountered a problem, where I want to support [`protoc-gen-openapiv2`](https://github.com/grpc-ecosystem/grpc-gateway/tree/main/protoc-gen-openapiv2) family of options, e.g. the message option in

```proto
syntax = "proto3";

import "protoc-gen-openapiv2/options/annotations.proto";

message OptionMessage {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "foo"
      ]
    }
  };
  string foo = 1;
};
```

When I convert this example with `buf build --output -#format=json`, with all the appropriate dependencies, I obtain a JSON representation of file descriptor that contains an `options` field populated with `[grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema]` option. When I pass this JSON to the `FileDescriptorSet` from `@bufbuild/protobuf` the instance of `FileDescriptorSet` then contains no options at all, therefor my plugin is unable to process the option. I stepped through the code and ended in 

https://github.com/bufbuild/protobuf-es/blob/c89f712e319e97491566e653a1a8bb439dc2edd3/packages/protobuf/src/private/json-format-common.ts#L66

Which is a little bit complicated to follow.

I was thinking that I will be able to extract the option with [findCustomMessageOption API](https://github.com/bufbuild/protobuf-es/blob/main/docs/writing_plugins.md#reading-custom-options) but when the option is missing in the `FileDescriptorSet` instance it is helpless.

I created a [repro through a test in Codesandbox](https://codesandbox.io/p/sandbox/protobuf-es-options-k4frdt?file=%2FfileDescriptor.test.js%3A27%2C11). To run the test, just use the integrated terminal and run `yarn test`.

**Comment by timostamm** [comment]
Thank you for the detailed issue, Václav!

The issue here is that this implementation don't support extensions yet (tracked in https://github.com/bufbuild/protobuf-es/issues/86). 

The option you are specifying is technically an extension of the [message google.protobuf.MessageOptions](https://github.com/protocolbuffers/protobuf/blob/8fc05442285a08d91f05995123fb02374d8b925e/src/google/protobuf/descriptor.proto#L528), and is serialized to JSON like a regular field, but with the name in brackets. When parsed again with `FileDescriptorSet.fromJson`, we don't recognize that it's an extension, and the option value is not available.

However, extracting the custom option should work if you simply store the set of descriptors in binary format instead of JSON. In the binary format, the value set by the custom option is retained as an [unknown field](https://protobuf.dev/programming-guides/proto3/#unknowns).

Let me know if that helps. We plan to support extensions soon.

**Comment by czabaj** [comment]
> extracting the custom option should work if you simply store the set of descriptors in binary format

That helped, thank you 🙇
