### ISSUE TITLE
Add CommonJS support as a plugin option

### ISSUE THREAD

**Issue by mfridman** [bufbuild/protobuf-es#587]
The current code generators (like `bufbuild/protobuf-es` and `connectrpc/es`) support ESM only. What do you think about adding an opt-in plugin option to modify the default behaviour?

As this project becomes more popular, it'd be nice for the generated code to "play nice" with the rest of the ecosystem. For example, some projects like NestJS do not work well with ESM-only. And the alternatives aren't great, such as importing the module asynchronously. 

Given that the Buf Schema Registry (BSR) hosts plugins with a pre-configured set of options, it means we'd need to publish a second plugin named based on the import. This isn't great, so something to think about.

https://buf.build/bufbuild/es vs https://buf.build/bufbuild/es-commonjs (does not exist)

Lastly, since we'll want this to be a "registry-compatible" plugin, we'll need a commonjs implementation for rewriting import paths.

**Comment by therockstorm** [comment]
From [this Slack thread](https://bufbuild.slack.com/archives/CRZ680FUH/p1696444329276079), without BSR support for CommonJS (and, by extension, NestJS), the "best" way to handle this is to bypass BSR completely and to instead create a monorepo with CI builds to generate CommonJS NPM packages.

Is this true? If so, how likely is Buf to support CommonJS and would we be talking months or years? If this is farther away than a couple of months, we'll have to move ahead with doing all of this ourselves and removing BSR from our workflow. NestJS has [no plans](https://github.com/nestjs/nest/issues/7021#issuecomment-831799620) to update to ESM. Another example: [this almost two year old PR](https://github.com/nestjs/nest/pull/8736).

**Comment by timostamm** [comment]
Hey Rocky, I am not sure that bypassing the BSR completely is the best workaround. NestJS does not support ESM-only npm packages, but it _does_ support TypeScript files with ESM imports.

For example, you might have an import like the following in your app:

```ts
// app.module.ts
import { AppController } from './app.controller';
```

This works in Nest, because all source files are transpiled to CJS.

If you generate code locally with protoc-gen-es, you can set the option `target=ts` to get the same result - TypeScript files with ESM imports. If you import them in your app, they will be transpiled to CJS like any other source file.

It isn't as neat as remote packages, but you can generate local code from remote protobuf files on the BSR. 

You need one configuration file:

```yaml
# buf.gen.yaml
version: v1
plugins:
  - plugin: buf.build/bufbuild/es
    out: src/gen
    opt: target=ts
  - plugin: buf.build/connectrpc/es
    out: src/gen
    opt: target=ts
```

Then you can run `buf generate` with any BSR module. For example:

```bash
$ buf generate buf.build/connectrpc/eliza
$ tree src/gen
src/gen
└── connectrpc
    └── eliza
        └── v1
            ├── eliza_connect.ts
            └── eliza_pb.ts

3 directories, 2 files
```

Your use case might vary, but right now, this would be my recommended approach with the BSR in case the framework does not support ESM.

**Comment by timostamm** [comment]
> Lastly, since we'll want this to be a "registry-compatible" plugin, we'll need a commonjs implementation for rewriting import paths.

This should not be necessary. Import statements are generated by `@bufbuild/protoplugin` here: https://github.com/bufbuild/protobuf-es/blob/fcf1a1e318ab2245b041cfb3a8d896be6ad7d515/packages/protoplugin/src/ecmascript/generated-file.ts#L206-L209

This could easily be extended to support CommonJS `require()` calls with a plugin option. The logic to rewrite import paths would continue to work as is.

The more challenging part are export statements. They are currently handwritten by plugins. In order to support CommonJS with a plugin option, we should provide an API to generate export statements, which automatically produces a ECMAScript export statement or a CommentJS export assignment, based on the plugin option.

**Comment by therockstorm** [comment]
@timostamm Thanks for the reply! Our use case:

We define EventBridge message schemas with Protobuf. Each message is sent from a single `producer` microservice to one or many `consumer` microservices. Each microservice is in a different GitHub repository.

We'd like the flow to work as follows:
1. In each `producer` repo, define Protobuf schemas and publish them to BSR
1. In each `consumer` repo, pull in BSR-generated assets for each `producer` you handle messages from and handle them

Since we can't use the BSR-generated assets, however, the flow is:
1. Same as above
1. In each `consumer` repo, run `buf generate buf.build/[PRODUCER_REPO]:[SOME_REF] --include-imports` to generate the `producer`'s proto files and handle messages

This works fine if a `consumer` is handling messages from a single `producer`. Anymore, however, and we run into dependency management issues. Say we have two `producer`s, P1 and P2. Both of their schemas depend on different versions of the Google Timestamp type (I realize this type is highly unlikely to differ between versions, especially in a breaking way, but bear with me).

Assuming we're generating these files into the same location, say `src/gen`, we need to ensure all of P1 and P2's dependencies are using the same versions or, at the very least, there aren't breaking changes between versions. The alternative is to use separate `out` directories for each `producer`, complicating the configuration. This also means every `consumer` is regenerating these files on each CI build with possibly differing versions of `@bufbuild/protoc-gen-es` and `@bufbuild/buf`, opening the door to hard to diagnose bugs that work fine in some repos but not others.

This all seems like a high price to pay just to use BSR with little benefit. Instead, it seems less error prone and produces less cognitive load for microservice developers to move all Protobuf schemas to a monorepo and generate the packages.

**Comment by timostamm** [comment]
Thanks for sharing the details on the use case, @therockstorm.

You _can_ re-use `buf.gen.yaml` files with the `--template` and `--output` flags. But I'd be the first to agree that remote packages are a better fit 🙂 

We have a couple of other features in the pipeline, but this will be implemented. It will most likely land before the end of the year.

**Comment by therockstorm** [comment]
That's excellent news, @timostamm! I was using https://github.com/timostamm/protobuf-ts prior to https://github.com/bufbuild/protobuf-es and they, along with the rest of the Buf tooling, are excellent to use. Thanks to the team for their efforts and for your helpful, fast responses here.

**Comment by krapie** [comment]
Wow, I really needed this option! Thanks!
I hope updated protobuf-es to be released ASAP :)

**Comment by smaye81** [comment]
Hi @krapie we just published v1.6.0 to npm: https://www.npmjs.com/package/@bufbuild/protobuf

**Comment by krapie** [comment]
@smaye81 Thank you for the release! But I'm still wondering why my `XXX_connect.js` is still using `export` statement, which causes ts-node `SyntaxError: Unexpected token 'export'` error.

![Screenshot 2023-12-13 at 11 42 19 AM](https://github.com/bufbuild/protobuf-es/assets/70474071/349225e0-4425-4a3f-be6d-d25938e056bb)

**Comment by krapie** [comment]
@timostamm Ohh, I thought this release updates all plugins to provide new option (I was able to use `js_import_style=legacy_commonjs` option on `connect-es`) 😄 

It is now working perfectly, thank you for your fast feedback and release!

**Comment by timostamm** [comment]
Just to provide context:

All plugins based on the plugin framework `@bufbuild/protoplugin` get the new option. protoc-gen-es, protoc-gen-connect-es, and protoc-gen-connect-query are all based on it. 

But the plugin framework can only modify export statements for CommonJS when it knows what the export statements are. For example, protoc-gen-connect-es was using this call to generate a service:

```ts
f.print("export const ", localName(service), " = {");
```

`"export const"` is just an opaque string to the plugin framework, and it would only be possible to modify it safely with a full parser, which is a big perf hit for large protobuf modules. So the latest release of the plugin framework adds a new method to generate export statements, and the latest release of protoc-gen-connect-es uses it:

```ts
f.print(f.exportDecl("const", localName(service)), " = {");
```

Similar to the already existing `f.import()`, this method generates a statement conditionally. Plugins must use `f.import()` and `f.exportDecl()` to fully support the new plugin option. More information is available in [the PR](https://github.com/bufbuild/protobuf-es/pull/648), and [in the documentation](https://github.com/bufbuild/protobuf-es/blob/main/docs/writing_plugins.md#why-use-fimport).
