### ISSUE TITLE
Investigate package-lock integrity issue

### ISSUE THREAD

**Issue by smaye81** [bufbuild/protobuf-es#589]
For full context, see #526 

The package-lock file seems to be missing `resolved` and `integrity` fields after installs in some instances. There is an open issue here with more context: https://github.com/npm/cli/issues/6301

The recommendation is to delete `node_modules` and `package-lock` and rerun the install, which is a fragile process. 

This PR is to track an investigation into whether we can implement a more permanent fix for this. Note the underlying cause is an issue with npm so we can't completely fix this, but we can at least harden our process to make sure these fields don't get removed.

**Comment by felschr** [comment]
Another, more popular npm issue about this: https://github.com/npm/cli/issues/4460

**Comment by felschr** [comment]
Nix builds packages in a declarative & fully reproducible way. That's why it needs to know the exact versions of all dependencies with their hashes.
The caching reference, you saw, due to Nix packages being built in isolation without network access.
Nixpkgs has some logic to download npm dependencies based on the lock file & then loads those dependencies into npm's cache and invokes `npm` cli in an offline mode.

There seems to be some work in nixpkgs to simplify working with incomplete/broken lock files, though:
https://github.com/NixOS/nixpkgs/issues/261137#issuecomment-1764673816

**Comment by smaye81** [comment]
Yeah I understand. It's good that there's some movement in nixpkgs for helping with this issue. It's a shame that the lock file is so non-deterministic like that. 

I am going to close this issue as there's nothing really for us to do here since this is an upstream bug. But if there's anything else on our side that could be addressed, let me know.

**Comment by timostamm** [comment]
https://github.com/bufbuild/protobuf-es/pull/750 will avoid removing the hash fields during a version bump. It's not a guarantee that we'll always have them, but it should help.
