### ISSUE TITLE
`Struct.fromJson()` panics when it encounters `undefined`

### ISSUE THREAD

**Issue by thesiti92** [bufbuild/protobuf-es#622]
i would expect the correct behavior to follow that of other messages and respect the `ignoreUndefinedFields` setting, or just ignore undefined values by default

pr: https://github.com/bufbuild/protobuf-es/pull/623

**Comment by srikrsna-buf** [comment]
Thank you for opening the issue along with a pr! 

The `ignoreUnknownFields` setting is to ignore any extra json fields of a message which are not part of the message definition. For example given the following proto:
```protobuf
message Some {
    string foo = 1;
}
```
If the json value the we receive is:
```json
{"foo": "...", "bar": "..."}
```

Then `bar` is the unknown field, and that is ignored.

Coming to `Struct`, it is part of special types called the [Well Known Types](https://protobuf.dev/reference/protobuf/google.protobuf/), it is designed to represent any json value. `undefined` is not a valid json value. For example, if I try to do `JSON.parse('{"foo": undefined}')` even js will throw an error. 

If you are using TypeScript, then the [`JsonValue`](https://github.com/bufbuild/protobuf-es/blob/8a230524bd753ba6efc954f12cd7bcf39fc42113/packages/protobuf/src/json-format.ts#L150) type ensures that a valid json value is passed to the method. The intention for `fromJson` is to typically pass the result of `JSON.parse` where instead of the raw json string we have the parsed object. So I'd say this is working as intended.

**Comment by thesiti92** [comment]
ok, we can work around it for now then. it would be helpful to at least have some flag to ignore the fields, or if you guys ever implement something like `.toPlainObject` and `.fromPlainObject`. We make extensive use of protobuf Structs and the current ways of manipulating them with protobuf-es are a bit cumbersome. either way thanks for looking over the pr!

**Comment by thesiti92** [comment]
oh nice, didnt realize you guys added that. I think for structs its a bit more effed because the plain message representation still looks like `{kind: <string>, value: <value>}` which isnt super ergonomic to work with. This is all perhaps a consequence of using protobuf structs in typescript at all haha
