### ISSUE TITLE
Serialize (toJson) Timestamp as date

### ISSUE THREAD

**Issue by Meemaw** [bufbuild/protobuf-es#703]
We use this package in combination with trpc & superjson. superjson is capable of serializing/deserializing dates. Is there a way to override how a certain type is serialized when calling `Message.toJson`?

For example, we would like to override `toJson` implementation of the `Timestamp` class.

**Comment by timostamm** [comment]
Hey Matej, the `Timestamp` message already has a special JSON representation - an ISO 8601 string:

```ts
import {Timestamp} from "@bufbuild/protobuf";
const ts = Timestamp.now();
console.log(
  ts.toJsonString() // "2024-02-07T11:59:44.546Z"
);
```

It's part of the Protobuf standard (documented [here](https://protobuf.dev/programming-guides/proto3/#json)), and if you were to change the serialized form, it would no longer be compatible to other Protobuf implementations. 

Are you seeing something else than the ISO format? It should parse just fine with most JS libraries if you need to, since it's the same format `Date` uses when serialized to JSON.

**Comment by Meemaw** [comment]
Hey @timostamm.

Yes, we have a bit of a unique use-case. We would like to override the `toJson` of `Timestamp` to return plain `Date` instead. This is because we later serialize the protobuf json object with `superjson`, which will preserve date objects when consumed on the client.

We were able to workaround by overriding the `Timestamp's` proto:

```js
Timestamp.prototype.toJson = function toJson() {
  const ms = Number(this.seconds) * 1000
  if (
    ms < Date.parse("0001-01-01T00:00:00Z") ||
    ms > Date.parse("9999-12-31T23:59:59Z")
  ) {
    throw new Error(
      `cannot encode google.protobuf.Timestamp to JSON: must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive`,
    )
  }
  if (this.nanos < 0) {
    throw new Error(
      `cannot encode google.protobuf.Timestamp to JSON: nanos must not be negative`,
    )
  }
  return new Date(ms)
}
```

This is probably a reasonable approach, and you probably don't want to support something like this in the library.

**Comment by timostamm** [comment]
Matej, overriding the method like this is an appropriate solution 👍 

You could wrap this into a function that overrides the method, serializes to JSON, then restores the method, so that it becomes free of side-effects.
