### ISSUE TITLE
JSON serialization options

### ISSUE THREAD

**Issue by nicole0707** [bufbuild/protobuf-es#737]
From the docs https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#json-serialization-options, `Message.fromJson` is supposed to allow some option like `enumAsInteger`.

However,  `JsonReadOptions` seems to include different options from code https://github.com/bufbuild/protobuf-es/blob/main/packages/protobuf/src/json-format.ts#L86. 

Just wondering if the doc is out of date,  is there any recommended way to support these options with `fromJSON` ? 

Cheers.

**Comment by timostamm** [comment]
Hey Nicole, when parsing an enum value from JSON, the full enum value name or the integer value are both accepted. 

So for the Protobuf `enum Foo { FOO_BAR=1 }`, both JSON values `"FOO_BAR"` and `1` parse the same. 

There isn't a JsonReadOption for it because both forms must be accepted to interop with other Protobuf implementations. If you serialize to JSON, you need to make a choice, so it is available as a JsonWriteOption.

**Comment by timostamm** [comment]
Oops, @smaye81 just pointed out I'm, wrong. Yes, the docs for "JSON serialization options" are swapped. Thanks for letting us know, @nicole0707.
