### ISSUE TITLE
Get T property of FieldInfo

### ISSUE THREAD

**Issue by nicole0707** [bufbuild/protobuf-es#738]
I am experimenting to retrieve `values` of enum FieldInfo, is there any existing API to get that? Otherwise, is it possible to export `fiPartialRules<fiScalar> | fiPartialRules<fiEnum> | fiPartialRules<fiMessage> | fiPartialRules<fiMap>` types for us? Thanks!

```ts
{
    kind: 'enum',
    no: 8,
    name: 'repayment_type',
    jsonName: 'repaymentType',
    T: {
      typeName: 'test.id.RepaymentType',
      values: [Array],
      findName: [Function: findName],
      findNumber: [Function: findNumber]
    },
    opt: true,
    default: undefined,
    localName: 'repaymentType',
    repeated: false,
    packed: true
  }
```

**Comment by timostamm** [comment]
Hey Nicole, Protobuf fields can be simple scalar values, but also message references, arrays (repeated field), or records (map fields). 

The `FieldInfo` type represents all of them as a union, with the "kind" property as a discriminator. We don't export the individual types, only the union. In fact, we don't even define individual types internally, because using the union type with the discriminator is usually sufficient. 

For example, we're walking through all fields here, and access the enum type for enum fields:

```ts
for (const fi of myMessage.getType().fields.list()) {
  if (fi.kind == "enum") {
    const enumType: EnumType = fi.T;
  }
}
```

The TypeScript compiler narrows down the `FieldInfo` union type with the check on the discriminator property, and knows that `T` is an `EnumType` inside the `if` block.

To refer to enum `FieldInfo`, you can use `FieldInfo & {kind:"enum"}`. For example, this function lists all enum fields:

```ts
function findEnumFields(messageType: MessageType) {
  const enumFields: (FieldInfo & {kind: "enum"})[] = [];
  for (const fi of messageType.fields.list()) {
    if (fi.kind == "enum") {
      enumFields.push(fi);
    }
  }
  return enumFields;
}
```

The result is an array of `FieldInfo` where `T` is guaranteed to refer to an `EnumType`.

We can take this one step further, to implement a function that finds an `EnumType` for a given field name:

```ts
function findEnum(messageType: MessageType, fieldName: string): EnumType | undefined {
  for (const fi of messageType.fields.list()) {
    if (fi.localName === fieldName) {
      if (fi.kind == "enum") {
        return fi.T;
      }
    }
  }
  return undefined;
}
```

Assuming you have a variable `messageType: MessageType` in scope, you would use it like this:

```ts
const enumType = findEnum(messageType, "myField");
if (enumType) {
  enumType.values;
}
```

Does this help?

**Comment by nicole0707** [comment]
Thanks @timostamm , it's really useful!

**Comment by timostamm** [comment]
Great, I'll close this 👍 

Future versions might allow this to work with type-safe field names.

**Comment by timostamm** [comment]
Type-safe conversion between an enum value and its JSON name is implemented in the [upcoming v2](https://github.com/bufbuild/protobuf-es/releases/tag/v2.0.0-alpha.1) by https://github.com/bufbuild/protobuf-es/pull/866.
