### ISSUE TITLE
Values missing if set to 0 and after converting toJson()

### ISSUE THREAD

**Issue by iamterryclark** [bufbuild/protobuf-es#762]
Hello,

I am running some tests to convert our google-protobuf setup to protobuf-es

we have a WebSocket receiving / requesting data between C++ and JavaScript

i have registered the types i am using and passing that to my unpack function.

I noticed that inside the message JSON after converting the incoming binary function that any value that was set to 0 goes missing from the json object

`event.data` is an `ArrayBuffer` so it needs to be converted to a `UInt8Array` it seems

``` js
 const data = new Uint8Array(event.data)
 const message = myMessagePacket.fromBinary(data);
 
 ...
 
//later i convert to json
 
const myMessage = message.anyTypedData.unpack(registry);

functionToPassBackToMyStateManmagement(myMessage.toJson())
 
```
I noticed printing `myMessage.toJson()` is missing any value which is set to 0.

**Comment by timostamm** [comment]
Hi Terry, this is expected behavior for fields that do not track presence. The field is also omitted when serializing to binary. 

You can pass the option `emitDefaultValues: true` as an argument to `toJson`. The option is documented [here](https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#json-serialization-options).

**Comment by smaye81** [comment]
This is because fields with default values are emitted from the JSON output by default according to the Protobuf JSON mapping.

If you'd like to preserve these fields in the output, you can use the `emitDefaultValues` option like so:

```typescript
myMessage.toJson({emitDefaultValues: true});
```

Our full docs are [here](https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#json-serialization-options).

**Comment by iamterryclark** [comment]
Thank you for the reply. I hadn't seen that.

Looking forward to have this library implemented on our app, in place of google-protobuf
