### ISSUE TITLE
Support for `google/api/field_behavior` ?

### ISSUE THREAD

**Issue by gimmyxd** [bufbuild/protobuf-es#764]
Hello, I'm trying to use https://github.com/googleapis/googleapis/blob/master/google/api/field_behavior.proto to define field behaviour, but seems that this is ignored:

```proto
syntax = "proto3";

package repro.v1;

import "google/api/field_behavior.proto";

message MyMessage {
  string field_required = 1
    [
        (google.api.field_behavior) = REQUIRED
    ];

  string field_optional = 2
    [
        (google.api.field_behavior) = OPTIONAL
    ];

  optional string force_optional = 3;
}

```

```ts
export class MyMessage extends Message<MyMessage> {
  /**
   * @generated from field: string field_required = 1;
   */
  fieldRequired = "";

  /**
   * @generated from field: string field_optional = 2;
   */
  fieldOptional = "";

  /**
   * @generated from field: optional string force_optional = 3;
   */
  forceOptional?: string;

  constructor(data?: PartialMessage<MyMessage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "repro.v1.MyMessage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "field_required", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "field_optional", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "force_optional", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);
```

As you can see both `field_required` and `field_optional` are require in the generated code.

Here is a repo with code: https://github.com/gimmyxd/field_behaviour_repro

**Comment by timostamm** [comment]
Hey Gheorghe, field_behavior.proto defines Protobuf options. Google uses these options, but I'm not aware of _any_ Protobuf implementation that supports them natively, and Protobuf-ES does not do so either.

Typically, support for field_behavior.proto would be implemented by looking at the field options of a message at runtime, and verifying if a given message satisfies the constraints.

Right now, this is not possible with Protobuf-ES, because you cannot inspect custom options at runtime. It's a feature we're currently working on, tracked in https://github.com/bufbuild/protobuf-es/issues/397. 

But please be aware that this might not do what you expect. The options will not change generated code, and they are independent of Protobuf language features like the `optional` keyword. 

Closing this, but please feel free to comment in case you have questions or I misunderstood 🙂
