### ISSUE TITLE
Serializing google.protobuf.Duration to JSON is not generic

### ISSUE THREAD

**Issue by realtimetodie** [bufbuild/protobuf-es#963]
When encoding `google.protobuf.Duration` to JSON, the output is being transformed into a string:

https://github.com/bufbuild/protobuf-es/blob/f76c9f528b8c9428893ab89f1fc8864c9d642870/packages/protobuf/src/to-json.ts#L481

This is unexpected. The output is opinionated and not generic. When using Protocol Buffer implementations of other languages, serialization of `google.protobuf.Duration` is not opinionated.

My suggestion is to remove the non-generic serializiation and serialize `google.protobuf.Duration` as is (into a JSON object).

Instead, a helper function could be provided, to serialize `google.protobuf.Duration` as it is right now.

I'm open to propose a PR myself but I would like to read the opinions of the maintainers first. Alternatively, I'm fine with a solution to prevent the `toJSON` serializer from transforming `google.protobuf.Duration` into a non-generic output.

**Comment by realtimetodie** [comment]
I also want to emphasize, that transforming `google.protobuf.Duration` into a non-generic output breaks type safety, because `google.protobuf.Duration` becomes a different type (string).

**Comment by timostamm** [comment]
Hey @realtimetodie, it is intentional that the message `google.protobuf.Duration` serializes to a string.  This is not a choice we made, it's part of the Protobuf standard.

The format is explained in a comment in the Protobuf source [here](https://github.com/protocolbuffers/protobuf/blob/v27.3/src/google/protobuf/duration.proto#L92-L100). You can find an overview of the JSON mapping [here](https://protobuf.dev/programming-guides/proto3/#json).

If you parse with `fromJson`, you'll see the expected Duration message. Other Protobuf implementations will serialize exactly the same. If they don't, it's a bug in the implementation.

**Comment by realtimetodie** [comment]
Hello @timostamm, thank you for your comprehensive answer. It helped me to better understand the reasoning for the serialization output.
